# Generated by Django 5.0.8 on 2024-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
